### ISSUE TITLE
DAQ sometimes crashes without obvious reason

### ISSUE THREAD

**Issue by JanGieseler** [LISE-B26/PyLabControl#50]
Not quite clear what is going on. Everything works fine over several hours and at some point the daq gives an error (see below)

Traceback (most recent call last):
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\core\scripts.py", line 378, in run
    
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\scripts\pulse_blaster_scripts.py", line 277, in _function
    self.scripts['Find_NV'].run()
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\core\scripts.py", line 378, in run
    
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\scripts\find_max_counts_point_2d.py", line 90, in _function
    self.scripts['take_image'].run()
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\core\scripts.py", line 378, in run
    
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\scripts\GalvoScanWithLightControl.py", line 60, in _function
    self.scripts['acquire_image'].run()
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\core\scripts.py", line 378, in run
    
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\scripts\galvo_scan.py", line 104, in _function
    self.instruments['daq']['instance'].AO_waitToFinish()
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\instruments\NIDAQ.py", line 480, in AO_waitToFinish
    float64(self.periodLength / self.AO_sample_rate * 2)))
  File "C:\Users\Experiment\PycharmProjects\PythonLab\src\instruments\NIDAQ.py", line 554, in _check_error
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buffer.value)))
RuntimeError: nidaq call failed with error -200560: 'Wait Until Done did not indicate that the task was done within the specified timeout.\n\nIncrease the'

**Comment by JanGieseler** [comment]
crashed again July 20th  2016 - same error msg

**Comment by JanGieseler** [comment]
crashed again July 22th 2016 - same error msg 1:30pm
 same line (104 in galvo_scan, now this is line 103)

**Comment by JanGieseler** [comment]
moved to b26_toolkit
