### ISSUE TITLE
Cannot combine parameter sweeps with loops (or likely any combination)

### ISSUE THREAD

**Issue by asafira** [LISE-B26/PyLabControl#98]
If you try to create a loop of a parameter sweep (or vice-versa), you get the following error:

Traceback (most recent call last):
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 800, in btn_clicked
    load_scripts()
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 696, in load_scripts
    data_path=data_folder_name)
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\core\scripts.py", line 972, in load_and_append
    script_info = ScriptIterator.create_dynamic_script_class(script_info)
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\core\script_iterator.py", line 509, in create_dynamic_script_class
    script_default_settings, sub_scripts = set_up_dynamic_script(script_information)
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\core\script_iterator.py", line 394, in set_up_dynamic_script
    raise NotImplementedError
NotImplementedError

It would be nice to be able to do this.

**Comment by JanGieseler** [comment]
fixed this partially. However, we should now also permit to sweep over subscript parameters. I thought this would not make sense but it does if one want to loop over a loop script
